[build]
  command = "gatsby build"
  publish = "public/"
  functions = "functions/"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"

[[plugins]]
  package = "@netlify/plugin-gatsby"

[[plugins]]
  package = "@netlify/plugin-form-submissions"

[forms]
  [forms."contact"]
    success_url = "/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
